sudo: required
services:
 - docker
 
before_install:
  - docker build -t OscarCiviero/docker-react -f Dockerfile.dev .
  
script:
 - docker run -e CI=true OscarCiviero/docker-react npm run test -- --coverage